### PR TITLE
Fix typo in copyright name in LICENSE

### LINKED ISSUE #130: Typo in license?
Hi 
I noticed that in package.json file the author name is Forrest L Norvell <ogd@aoaioxxysz.net>, but in license, the copyright is for Forrest L Norvel. Just want to make sure if there is a typo. 

Thanks!

### PR DESCRIPTION
**Pull request by watson**
Fixes #130

### CODE REVIEW

**Comment by johnjbarton** [comment]
Could you please include the LICENSE file in the npm?

**Comment by watson** [comment]
@johnjbarton it should already be included. We don't exclude anything in the published npm package. Don't you see it?

**Comment by ofrobots** [comment]
I think the issue is that there hasn't been a release since the LICENSE file was added. The next release should have it.

**Comment by watson** [comment]
@ofrobots Ah good point - I missed that. I don't see any issue making a patch release now if this is important for @johnjbarton to have before he can use it. If nobody have any objections against merging this PR then I'll make a release ASAP

**Comment by johnjbarton** [comment]
I checked and the LICENSE file in the npm is only need to avoid manually creating one on our side from the info in your repo.  So it saves us a little work, reducing friction on updates, but release when you need to, not for LICENSE.  Thanks (and thanks for async-listener)!

**Pull request merged**
