### PR TITLE
Patch http.Agent pools

### PR DESCRIPTION
**Pull request by Qard**
This should properly resolve #61 and https://github.com/othiym23/node-continuation-local-storage/issues/71.

### CODE REVIEW

**Comment by Qard** [comment]
@othiym23 @hayes @matthewloring Anyone care to give this a look? It fixes an issue with http.Agent connection pools not triggering before/after for reused sockets and therefore causing CLS to lose context when the pooling kicks in.

**Comment by jchip** [comment]
👍 
This doesn't work if https://github.com/node-modules/agentkeepalive is used though.  I am trying to understand what that agent brings in addition to `http.Agent` though.

**Comment by Qard** [comment]
Seems like `agentkeepalive` is actually broken on node v5+. It should take a callback rather than returning a socket: https://github.com/nodejs/node/blob/master/lib/_http_agent.js#L149.

**Comment by Qard** [comment]
Merged and released in 0.6.1.

**Pull request merged**
