### PR TITLE
v1.0.0

### PR DESCRIPTION
**Pull request by jacobp100**
I think this API is stable. Would it make sense to ship v1 and follow semver?

### CODE REVIEW

**Comment by jacobp100** [comment]
The reason for this is that one of the versions breaks on node 11.

`aws-xray-sdk` depends on this through `aws-xray-sdk` -> `aws-xray-sdk-core` -> `node-continuation-local-storage` -> this package.

It looks like `node-continuation-local-storage` is no longer developed, so it hasn't merged anything to bump the version of this package.

As a result, aws is switching out the `node-continuation-local-storage` package, even though that isn't the broken package.

If semver had been used, this would have automatically been fixed. We can't fix the issue with aws with this, but we can try and avoid this in the future! 😃

**Comment by rochdev** [comment]
Before releasing v1.0.0 it would probably be wise to fix the known [memory leak](https://github.com/othiym23/async-listener/issues/124) when throwing from a native `Promise` handler (which is very common).

**Comment by jacobp100** [comment]
1.0.0 just means API stability, it doesn't necessarily mean it's bug free! 😀

**Comment by carlisliu** [comment]
agreed, higher version of node.js should use native `async_hooks ` module.

**Comment by rochdev** [comment]
@carlisliu `async_hooks` is only available in Node >=8 but native `Promise` was introduced in Node 4. This library is one of the only options from >=4 to <8 but is currently unusable because of the leak.

**Comment by Qard** [comment]
v4 is EOL, and v6 is not far off from that too. I don't think motivation is very high to deal with super old versions of Node.js...

That being said, PRs are welcome. 🤷‍♂️

**Pull request closed without merging**
