### PR TITLE
run core tests

### PR DESCRIPTION
**Pull request by hayes**

### CODE REVIEW

**Comment by hayes** [comment]
this just adds a runner for the core tests so they get included in the `npm test` run, and update some of the tests to use the new api format.  One fails, buts that is an existing bug in cls.

**Comment by othiym23** [comment]
> One fails, buts that is an existing bug in cls.

What's the bug in CLS? I see a failure in `core-asynclistener.simple.js`:

```
% node test/core-asynclistener.simple.js
expected 29
actual   30

assert.js:87
  throw new assert.AssertionError({
        ^
AssertionError: 30 == 29
    at process.<anonymous> (/Users/ogd/Documents/projects/async-listener/test/core-asynclistener.simple.js:49:10)
    at emitOne (events.js:77:13)
    at process.emit (events.js:166:7)
```

but that test file has always been among the more opaque. I can probably go in and use `process._rawDebug` to figure out what's broken, but if there's an issue you know about, it would save me time.

**Comment by hayes** [comment]
Sorry that is a type, the bug is in async-listener.  Give me a minute, I'll try to find the minimal repro

**Comment by hayes** [comment]
this is the test: https://github.com/othiym23/async-listener/blob/master/test/core/core-asynclistener-error-throw-in-before-inflight.js

The bug is essentially that the list that is passed to asyncWrap is the same object that the set of active listeners in a scope is using, so if listeners are added/removed on the same tick after an async context has already been created, the list of listeners that applies to that async context will also change

**Pull request closed without merging**
