### PR TITLE
fix http tests on node 8

### PR DESCRIPTION
**Pull request by hayes**
Tests have not been passing on node 8.  This should get them passing again, but I I did not properly dig into whether or not changing the tests is the right thing, or if there is something that was broken in the instrumentation. 

I suspect that changing the tests is safe here, but further investigation is probably required to ensure nothing was actually broken.

### CODE REVIEW

**Comment by watson** [comment]
As far as I know there's nothing wrong with the tests in Node 7 (except for the thing that's actually a bug in Node it self). Which things failed in Node 7?

**Comment by hayes** [comment]
You are correct, I initially had.added an exception for that but in this PR before I really understood the issue, I should update the commit message and PR description

**Comment by watson** [comment]
Cool 👍 And thanks for taking the time to fix this 👊 I guess this then takes care of my concern in https://github.com/othiym23/async-listener/pull/115#issuecomment-309001493 if we can merge it soon

**Comment by hayes** [comment]
Dug in a little more, and I am pretty confident everything is working correctly on node 8, so this should be good to merge.

**Pull request merged**
