### PR TITLE
wrap socket ref/unref to handle socket reuse by keep alive

### PR DESCRIPTION
**Pull request by jchip**
resolves https://github.com/othiym23/node-continuation-local-storage/issues/71

### CODE REVIEW

**Comment by Qard** [comment]
Unfortunately I don't think this is quite the solution needed. The `ref` and `unref` function can be called in other ways than just for socket reuse. Re-binding `onread` to the context at the point where the `ref` is used may be incorrect, depending on usage. I'm currently exploring solutions to this issue myself, but it's proving to be complicated.

**Comment by jchip** [comment]
That's a good point.  

I don't really see an easy way to detect this looking at socket's document. 

https://nodejs.org/api/net.html#net_class_net_socket

I wonder what's the likelihood of `ref` and `unref` being used in other ways.

However, if you are using CLS, you should know what you are doing and understand the nature of using something like that.  wrapping `ref` and `unref` is the cleanest way I see for now.  I think being able to use keep alive and keep CLS context is more important than the potential of `ref` and `unref` being used in other ways.

Looking at http code, looks like `setKeepAlive` is called before `unref`, maybe we can use that.

https://github.com/nodejs/node/blob/v4.x/lib/_http_agent.js#L73

**Comment by jchip** [comment]
Another note, if there are other existing uses of `ref` and `unref`, it just means CLS context would break in different ways.  It could be either worst than current situation, or not, depending on particular needs.    I don't know if there are existing uses of `ref` and `unref` other than for keep alive though.

**Comment by Qard** [comment]
It's fairly common to use `unref` to let the event loop end if no other active handles are running, letting the process terminate without waiting for the socket to close. I don't expect it'd be very common to use CLS in that sort of environment, so it *may* be okay. I think there may be an issue in there with concurrent socket use in the http.Agent pool though. I'm still looking into it.

**Pull request closed without merging**
